name: Triple Square Sum Finder (GPU)

on:
  workflow_dispatch: # 手动触发执行
  push:
    branches:
      - main

jobs:
  calculate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install NVIDIA Drivers
        run: |
          sudo apt-get update
          sudo apt-get install -y nvidia-driver-470

      - name: Install Python dependencies
        run: |
          pip install cupy tqdm

      - name: Run the Python script
        run: python script.py
