name: Triple Square Sum Finder (GPU)

on:
  workflow_dispatch: # 手动触发执行
  push:
    branches:
      - main

jobs:
  calculate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install NVIDIA Drivers and Toolkit
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential dkms
          distribution=$(. /etc/os-release; echo $ID$VERSION_ID) && \
          curl -fsSL https://nvidia.github.io/nvidia-docker/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg && \
          curl -fsSL https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | \
          sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
          sudo apt-get update
          sudo apt-get install -y nvidia-container-toolkit
          sudo systemctl restart docker

      - name: Verify NVIDIA Toolkit Installation
        run: |
          nvidia-smi || echo "NVIDIA driver is not working properly. Please check the installation."

      - name: Run GPU-accelerated Docker container
        run: |
          docker run --rm --gpus all \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace nvidia/cuda:11.8.0-base-ubuntu20.04 \
          bash -c "apt update && apt install -y python3 python3-pip && pip3 install cupy tqdm && python3 script.py"
